### ISSUE TITLE
Access to on-board speaker and microphone?

### ISSUE THREAD

**Issue by orm-github** [murilopolese/kano-pixel-kit-pixel32#20]
Hello,
Which GPIO's of the ESP32 are used to access and receive sound from the microphine and modulate/control the on-board speaker?

Also, I am considering adding an I2C based BME680 Temp/Humidity/Pressure/Gas sensor, are there any convenient was to get access to unused GPIO's without soldering directly to ESP32 module?

Thanks, in advance, for any help!

**Comment by RUGMJ** [comment]
Did you ever find the ports for the microphone and / or speaker?

**Comment by darryllee** [comment]
According to this [reddit post](https://www.reddit.com/r/esp32/comments/om2bee/pinouts_for_kano_pixel_kit/): 
> MIC is on GPIO 39 ADC1_3. Looks like it's an analog mems that's not i2s.

**Comment by murilopolese** [comment]
https://github.com/murilopolese/kano-pixel-kit-pixel32/pull/23

**Comment by goglesquirmintontheiii** [comment]
Adding to what's already been said, as far as I am aware, there is no speaker on the pixel kit, only a microphone. Also, you might be able to use some USB-to-serial dongle or such for the sensor, as there should be some way to access the USB ports on the top of the kit using micropython. Other than that, there's no pins or ports to plug into, so you'll probably just have to find a free GPIO pin and solder to it.

**Comment by colinvail6** [comment]
The buzzer/speaker appears to be on GPIO22. I have not tested this yet

**Comment by colinvail6** [comment]
GPIO22 ------ Transistor ------ Buzzer

**Comment by colinvail6** [comment]
Actually it is GPIO22 ------ Resistor (R9) ------ Transistor (Q1) ------ Buzzer
