### ISSUE TITLE
How to forget wifi network on Pixel Kit

### ISSUE THREAD

**Issue by JoshAtticus** [murilopolese/kano-pixel-kit-pixel32#21]
I've gotten a new WiFi network, and I can't get the WiFi to connect, it just shows a red screen. Any tips? Thank you!

**Comment by darryllee** [comment]
Ohey! You need to get to the "blue screen":
> Blue: Created its own wifi network. It should be named something like PIXEL_KIT_XXXX but with a number instead of the XXXX.
To do this:
> At any time, turn your Pixel Kit off and on again while holding both red buttons to gently force it to show the blue screen.

(Found in the docs, but it's not entirely obvious: https://murilopolese.github.io/kano-pixel-kit-pixel32-docs/pixel32)

**Comment by murilopolese** [comment]
That is how you do indeed!

> At any time, turn your Pixel Kit off and on again while holding both red buttons to gently force it to show the blue screen.
