### ISSUE TITLE
Blockly integration?

### ISSUE THREAD

**Issue by klausw** [murilopolese/kano-pixel-kit-pixel32#6]
Kano Code is based on Google Blockly, and there seem to be a few projects implementing a MicroPython output backend for Blockly, i.e. https://github.com/bbcmicrobit/PythonEditor and https://github.com/marekmansell/ESPBlocks .

Would it be feasible to integrate a Blockly editor with MicroPython? Ideally this would be compatible with on-device user program storage (see issue #5).

It would be awesome if there were some level of compatibility with Kano Code's Blockly programs for the Pixel Kit, at least for basic actions such as simple lightboard integration. (Complex custom blocks such as animations on Pixel Kit would likely be harder, but personally I'm less interested in those.)

**Comment by murilopolese** [comment]
Hey, @klausw !

That is a great suggestion and I'll definitely ping people at Kano about that. On the other hand, block code is outside of the scope of Pixel32 for now as its focus is on text based programming.

Interesting enough, the main idea is that Pixel32 is just one way/flavor to interact with MicroPython on the Pixel Kit and if you use the [Pixel Kit Flash Tool](https://github.com/murilopolese/kano-pixel-kit-flash-tool) is what will come by default. Different people learn in different ways and should be allowed to use different tools for it 🛠😄 

Answering your question: It's 100% feasible to have a blockly interface for Pixel Kit running MicroPython. Once your Pixel Kit is running MicroPython and with WebREPL active, there shouldn't be a huge deal to use the [webrepl-client](https://github.com/murilopolese/webrepl-client) to send Python code created by a blockly interface. This is just outside of the Pixel32 scope but it might be something worth prototyping. If you want to give a try me, count on me to contribute to it 👯
